package com.pojo;

// Generated Mar 30, 2018 3:48:21 AM by Hibernate Tools 3.4.0.CR1

/**
 * Criminaldetail generated by hbm2java
 */
public class Criminaldetail implements java.io.Serializable {

	private Integer criminalNo;
	private String name;
	private String address;
	private String city;
	private String mobileno;
	private String information;

	public Criminaldetail() {
	}

	public Criminaldetail(String name, String address, String city, String mobileno, String information) {
		this.name = name;
		this.address = address;
		this.city = city;
		this.mobileno = mobileno;
		this.information = information;
	}

	public Integer getCriminalNo() {
		return this.criminalNo;
	}

	public void setCriminalNo(Integer criminalNo) {
		this.criminalNo = criminalNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

}
