package com.pojo;

// Generated Mar 30, 2018 3:48:21 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Registration implements java.io.Serializable {

	private Integer regNo;
	private Role role;
	private String stationname;
	private String fname;
	private String lname;
	private String address;
	private String city;
	private String email;
	private String password;
	private String mobileno;
	private Set theftrecords = new HashSet(0);
	private Set firrecords = new HashSet(0);
	private Set missingrecords = new HashSet(0);

	public Registration() {
	}

	public Registration(Role role, String stationname, String fname, String lname, String address, String city,
			String email, String password, String mobileno, Set theftrecords, Set firrecords, Set missingrecords) {
		this.role = role;
		this.stationname = stationname;
		this.fname = fname;
		this.lname = lname;
		this.address = address;
		this.city = city;
		this.email = email;
		this.password = password;
		this.mobileno = mobileno;
		this.theftrecords = theftrecords;
		this.firrecords = firrecords;
		this.missingrecords = missingrecords;
	}

	public Integer getRegNo() {
		return this.regNo;
	}

	public void setRegNo(Integer regNo) {
		this.regNo = regNo;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getStationname() {
		return this.stationname;
	}

	public void setStationname(String stationname) {
		this.stationname = stationname;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	public Set getTheftrecords() {
		return this.theftrecords;
	}

	public void setTheftrecords(Set theftrecords) {
		this.theftrecords = theftrecords;
	}

	public Set getFirrecords() {
		return this.firrecords;
	}

	public void setFirrecords(Set firrecords) {
		this.firrecords = firrecords;
	}

	public Set getMissingrecords() {
		return this.missingrecords;
	}

	public void setMissingrecords(Set missingrecords) {
		this.missingrecords = missingrecords;
	}

}
