package com.pojo;

// Generated Mar 30, 2018 3:48:21 AM by Hibernate Tools 3.4.0.CR1

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private Integer statusNo;
	private Firrecord firrecord;
	private Missingrecord missingrecord;
	private Theftrecord theftrecord;
	private String usertype;
	private String status;

	public Status() {
	}

	public Status(Firrecord firrecord, Missingrecord missingrecord, Theftrecord theftrecord, String usertype,
			String status) {
		this.firrecord = firrecord;
		this.missingrecord = missingrecord;
		this.theftrecord = theftrecord;
		this.usertype = usertype;
		this.status = status;
	}

	public Integer getStatusNo() {
		return this.statusNo;
	}

	public void setStatusNo(Integer statusNo) {
		this.statusNo = statusNo;
	}

	public Firrecord getFirrecord() {
		return this.firrecord;
	}

	public void setFirrecord(Firrecord firrecord) {
		this.firrecord = firrecord;
	}

	public Missingrecord getMissingrecord() {
		return this.missingrecord;
	}

	public void setMissingrecord(Missingrecord missingrecord) {
		this.missingrecord = missingrecord;
	}

	public Theftrecord getTheftrecord() {
		return this.theftrecord;
	}

	public void setTheftrecord(Theftrecord theftrecord) {
		this.theftrecord = theftrecord;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
