package com.pojo;

// Generated Mar 30, 2018 3:48:21 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Theftrecord generated by hbm2java
 */
public class Theftrecord implements java.io.Serializable {

	private Integer theftNo;
	private Registration registration;
	private String theftthing;
	private String theftthingaddress;
	private String theftthingcity;
	private String information;
	private Set statuses = new HashSet(0);

	public Theftrecord() {
	}

	public Theftrecord(Registration registration, String theftthing, String theftthingaddress, String theftthingcity,
			String information, Set statuses) {
		this.registration = registration;
		this.theftthing = theftthing;
		this.theftthingaddress = theftthingaddress;
		this.theftthingcity = theftthingcity;
		this.information = information;
		this.statuses = statuses;
	}

	public Integer getTheftNo() {
		return this.theftNo;
	}

	public void setTheftNo(Integer theftNo) {
		this.theftNo = theftNo;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public String getTheftthing() {
		return this.theftthing;
	}

	public void setTheftthing(String theftthing) {
		this.theftthing = theftthing;
	}

	public String getTheftthingaddress() {
		return this.theftthingaddress;
	}

	public void setTheftthingaddress(String theftthingaddress) {
		this.theftthingaddress = theftthingaddress;
	}

	public String getTheftthingcity() {
		return this.theftthingcity;
	}

	public void setTheftthingcity(String theftthingcity) {
		this.theftthingcity = theftthingcity;
	}

	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

	public Set getStatuses() {
		return this.statuses;
	}

	public void setStatuses(Set statuses) {
		this.statuses = statuses;
	}

}
